title: Mystery Monster Mayhem! Alpha
description: Online documentation for Mystery Monstery Mayhem! Alpha
theme: just-the-docs

url: https://whensuddenlygames.github.io/MysteryMonsterMayhem

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

  # Color scheme supports "light" (default) and "dark"
color_scheme: scooby

logo: "imgs/just-the-docs.png"
